apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-sample
  namespace: default
  labels:
    serviceapp: demo-service
spec:
  selector:
    matchLabels:
      service: nginx
  endpoints:
  - port: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - default